/**********************************************************************************************************************
 * \file SPI_Frontend.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SPI_Frontend.h"
#include "CRC8_SAE_J1850.h"
#include "IfxPort.h"
#include "time.h"
#include "spi.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
// VALID CMTP WRITE VALUES
const uint16 OTP_254_CONTENT_OK   = 0x6088;
const uint16 OTP_255_CONTENT_OK   = 0x0317;
const uint16 OTP_DUMMY_CONTENT_OK = 0xF16B;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void InitSPI( void )
{
    // Init SPI module
    initQSPI();
}

uint32 SpiWriteInFrame(uint8 addr, uint16 data)
{
    static uint8 data_temp[4]     = {0,0,0,0};
    static uint8 r_w                 = 1;

    /* Set the appropriate bits for Writing in frame */
    data_temp[0] = (addr << 1) | (r_w & 1);     // 7bit address 1 bit R/W
    data_temp[1] = (data >> 8) & 0xFF;          // 1 data byte MSB
    data_temp[2] = data & 0xFF;                 // 1 data byte LSB
    data_temp[3] = CalcCRC(data_temp, 3);       // 1 byte CRC

    // Send the data through the SPI channel
    return SpiSendAndReceive(data_temp);
}

uint32 SpiReadInFrame(uint8 addr, uint8 clearStatus)
{

    static uint8 data_temp[4]     = {0,0,0,0};
    static uint8 r_w                 = 0;

    /* Set the appropriate bits for Reading in frame */
    data_temp[0] = (addr << 1) | (r_w & 1);     // 7bit address 1 bit R/W
    data_temp[1] = 0x00;                        // Unused
    if(clearStatus)
    {
        data_temp[2] = 0xFF;                    // All 1s clear device status bit
    }
    else
    {
        data_temp[2] = 0x00;                    // All 0s no clearing
    }
    data_temp[3] = CalcCRC(data_temp, 3);       // 1 byte CRC

    // Send the data through the SPI channel
    return SpiSendAndReceive(data_temp);
}


uint32 SpiSendAndReceive(uint8* data_temp)
{
    // Concatenate the data to be sent
    uint32 send_data = ((data_temp[0] << 24) | (data_temp[1] << 16) | (data_temp[2] << 8) | data_temp[3]);

    // Send the data through the SPI channel
    return SpiMasterSendAndReceive(send_data);
}







