/**********************************************************************************************************************
 * \file SPI_Frontend.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef SRC_TLX49012_SPI_FRONTEND_SPI_FRONTEND_H_
#define SRC_TLX49012_SPI_FRONTEND_SPI_FRONTEND_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "CRC8_SAE_J1850.h"
#include "IfxPort.h"
#include "time.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
// UNLOCK                               - Same for A11 & B11
#define IFX_PASS        0xAFFE
#define USR_PASS        0x4711
#define UNLOCK_REG      120

// DEFINE FOR ACCESS RIGHTS
#define IFX_ACCESS 200
#define USR_ACCESS 1

// CRC BitMap Disable                   - Same for A11 & B11
#define STAT_EN_1_REG   4
#define CRC_BM_DIS      0x7E18

// CMTP STATUS                          - Same for A11 & B11
#define CMTP_STAT_REG   254
#define CMTP_STAT_REG2  255
#define MASK_STATUS_REG_254_PROG_CYCLES 0x1F00

// CMTP                                 - Same for A11 & B11
#define CMTP_MEMORY_START       256
#define CMTP_MEMORY_STOP_A11    315

/*
// SW RESET
#define STAT_EN_REG         2
#define SOFT_RESET_VM_DATA  0x83A2
#define SOFT_RESET_NVM_DATA 0x83A1
*/

// NEXT FRAME COMMANDS
#define CMD_ADDR        0xFF
#define CMD_END         0xFE
#define CMD_DATA_ADDR   0xFD

// REGISTER ACCESS TYPE
#define AC_READ_INC     0
#define AC_WRITE_CONT   1
#define AC_WRITE_INC    2

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef struct {
    uint8 otp_255_status;
    uint8 otp_254_status;
    uint8 otp_dummy;
} T_ProgramStatusReturn;

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void InitSPI( void );


uint32 EnterTestMode(uint8 accessRights);
void ExitTestMode();
uint32 SpiWriteInFrame(uint8 addr, uint16 data);
uint32 SpiReadInFrame(uint8 addr, uint8 clearStatus);
uint32 SpiCommandNextFrame(uint16 addr, uint8 accessType);
uint32 SpiEndCommandNextFrame();
uint32 SpiWriteNextFrame(uint16 data);
uint32 SpiReadNextFrame(uint8 clearStatus);
uint32 SpiReadRegNextFrame(uint16 addr, uint8 clearStatus);
uint32 SpiWriteRegNextFrame(uint16 addr, uint16 data);
uint32 SpiSendAndReceive(uint8* data_temp);
uint32 VM_SoftReset();
uint32 NVM_SoftReset();
uint32 VM_SoftResetTestMode(uint8 accessRights);
void ReadMemoryNxF(uint16 *mem, uint16 start_addr, uint16 stop_addr);
void ReadWriteCyclesCMTP(uint16 *mem, uint16 start, uint16 stop);
T_ProgramStatusReturn WriteCMTPLine(uint16 address, uint16 value);

#endif /* SRC_TLX49012_SPI_FRONTEND_SPI_FRONTEND_H_ */
