/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

//For more info regarding the calibration of this type of device you can visit:
//https://www.infineon.cn/row/public/documents/24/42/infineon-tle5xxxd-calibration-360-an-applicationnotes-en.pdf

/*This is a project example of the one-point calibration for TLE5501 devices on the Aurix TC334 Platform. (AURIX TCxx4 lite Kit)
It uses 4 channels of EVADC to read the 4 inputs from the sensor: SINN, COSN, SINP, COSP.

*/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "Ifx_Cfg_Ssw.h"

#include "IfxEvadc_Adc.h"
#include "IfxSrc.h"
#include "IfxCpu_Irq.h"
#include <Evadc/Adc/IfxEvadc_Adc.h>
#include <ongocalib.h>
#include <stdio.h>

IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;


/*PINS on Lite kit TC334
 *  ADC0 - AN39 - P40.9
 *  ADC1 - AN38 - P40.8
 * Cos N -A3 (on shield) =  ADC2 - AN37 - P40.7 - EVADC_G8CH5
 * Sin N -A2 (on shield) =  ADC3 - AN36 - P40.6 EVADC_G8CH4
 * Cos P -A1 (on shield) =  ADC4 - AN33 - P40.5 EVADC_G8CH1
 * Sin P -A0 (on shield) = ADC5 - AN32 - P40.4 EVADC_G8CH0
 */

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);
    
    evadc_g8_init_queue_continuous();

    ONGO_CALIB_DATA_t calibration_store_params;

    float64_t angle_new = 0;
    float64_t angle_read = 0;
    uint32_t sinP_in_LSB = 0;
    uint32_t cosP_in_LSB = 0;
    uint32_t sinN_in_LSB = 0;
    uint32_t cosN_in_LSB = 0;


    sinP_in_LSB = AnalogRead(3);
    cosP_in_LSB = AnalogRead(2);
    sinN_in_LSB = AnalogRead(1);
    cosN_in_LSB = AnalogRead(0);
    ONGO_InitCalibData3(&calibration_store_params);
    ONGO_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);

    int fails = 0;
    int passes = 0;
    while(1)
    {

        // read sensor data
        // AnalogRead(ch) is a user defined function to read the analog voltage on P and N channels

        sinP_in_LSB = AnalogRead(3);
        cosP_in_LSB = AnalogRead(2);
        sinN_in_LSB = AnalogRead(1);
        cosN_in_LSB = AnalogRead(0);
        ONGO_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);

        ONGO_CalibrationFindParam(&calibration_store_params);

        if(SME1_angleComparison_AutoCalibration(&calibration_store_params)) //if true passes, if false fails
        {
            passes++;
        }
        else
        {
            fails++;
        }
        if( SME2_1_vectorLength_AutoCalibration(&calibration_store_params)) //if true passes, if false fails
        {
            passes++;
        }
        else
        {
            fails++;
        }
        if(SME2_2_vectorLengthCheck_AutoCalibration(&calibration_store_params)) //if true passes, if false fails
        {
            passes++;
        }
        else
        {
            fails++;
        }
        if(SME2_3_vectorLengthCheck_AutoCalibration(&calibration_store_params)) //if true passes, if false fails
        {
            passes++;
        }
        else
        {
            fails++;
        }
        if(SME3_commonModeCheck(&calibration_store_params)) //if true passes, if false fails
        {
            passes++;
        }
        else
        {
            fails++;
        }

        angle_read = ONGO_GetCalibAngle(&calibration_store_params);
    }



}

