/**
 * \file IfxPort_PinMap_TC33x_TQFP100.c
 * \brief PORT I/O map
 * \ingroup IfxLld_Port
 *
 * \version iLLD_1_20_0
 * \copyright Copyright (c) 2024 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 */
#include "Ifx_Cfg.h"
#if defined (__TASKING__)
#pragma warning 508		/* To suppress empty file warning */
#endif
#if defined (__ghs__)
#pragma diag_suppress 96		/* To suppress empty file warning */
#endif
#if defined DEVICE_TC33X && defined IFX_PIN_PACKAGE_TQFP100

#include "IfxPort_PinMap_TC33x_TQFP100.h"

IfxPort_Pin IfxPort_P00_0 = {&MODULE_P00, 0};
IfxPort_Pin IfxPort_P02_0 = {&MODULE_P02, 0};
IfxPort_Pin IfxPort_P02_1 = {&MODULE_P02, 1};
IfxPort_Pin IfxPort_P02_2 = {&MODULE_P02, 2};
IfxPort_Pin IfxPort_P02_3 = {&MODULE_P02, 3};
IfxPort_Pin IfxPort_P02_4 = {&MODULE_P02, 4};
IfxPort_Pin IfxPort_P02_5 = {&MODULE_P02, 5};
IfxPort_Pin IfxPort_P02_6 = {&MODULE_P02, 6};
IfxPort_Pin IfxPort_P02_7 = {&MODULE_P02, 7};
IfxPort_Pin IfxPort_P02_8 = {&MODULE_P02, 8};
IfxPort_Pin IfxPort_P10_5 = {&MODULE_P10, 5};
IfxPort_Pin IfxPort_P10_6 = {&MODULE_P10, 6};
IfxPort_Pin IfxPort_P11_10 = {&MODULE_P11,10};
IfxPort_Pin IfxPort_P11_11 = {&MODULE_P11,11};
IfxPort_Pin IfxPort_P11_12 = {&MODULE_P11,12};
IfxPort_Pin IfxPort_P11_2 = {&MODULE_P11, 2};
IfxPort_Pin IfxPort_P11_3 = {&MODULE_P11, 3};
IfxPort_Pin IfxPort_P11_6 = {&MODULE_P11, 6};
IfxPort_Pin IfxPort_P11_8 = {&MODULE_P11, 8};
IfxPort_Pin IfxPort_P11_9 = {&MODULE_P11, 9};
IfxPort_Pin IfxPort_P13_1 = {&MODULE_P13, 1};
IfxPort_Pin IfxPort_P13_2 = {&MODULE_P13, 2};
IfxPort_Pin IfxPort_P13_3 = {&MODULE_P13, 3};
IfxPort_Pin IfxPort_P14_0 = {&MODULE_P14, 0};
IfxPort_Pin IfxPort_P14_1 = {&MODULE_P14, 1};
IfxPort_Pin IfxPort_P14_3 = {&MODULE_P14, 3};
IfxPort_Pin IfxPort_P14_5 = {&MODULE_P14, 5};
IfxPort_Pin IfxPort_P15_0 = {&MODULE_P15, 0};
IfxPort_Pin IfxPort_P15_1 = {&MODULE_P15, 1};
IfxPort_Pin IfxPort_P15_2 = {&MODULE_P15, 2};
IfxPort_Pin IfxPort_P15_3 = {&MODULE_P15, 3};
IfxPort_Pin IfxPort_P15_5 = {&MODULE_P15, 5};
IfxPort_Pin IfxPort_P20_10 = {&MODULE_P20,10};
IfxPort_Pin IfxPort_P20_11 = {&MODULE_P20,11};
IfxPort_Pin IfxPort_P20_12 = {&MODULE_P20,12};
IfxPort_Pin IfxPort_P20_13 = {&MODULE_P20,13};
IfxPort_Pin IfxPort_P20_14 = {&MODULE_P20,14};
IfxPort_Pin IfxPort_P20_8 = {&MODULE_P20, 8};
IfxPort_Pin IfxPort_P20_9 = {&MODULE_P20, 9};
IfxPort_Pin IfxPort_P21_2 = {&MODULE_P21, 2};
IfxPort_Pin IfxPort_P21_3 = {&MODULE_P21, 3};
IfxPort_Pin IfxPort_P21_4 = {&MODULE_P21, 4};
IfxPort_Pin IfxPort_P21_6 = {&MODULE_P21, 6};
IfxPort_Pin IfxPort_P21_7 = {&MODULE_P21, 7};
IfxPort_Pin IfxPort_P23_1 = {&MODULE_P23, 1};
IfxPort_Pin IfxPort_P33_10 = {&MODULE_P33,10};
IfxPort_Pin IfxPort_P33_5 = {&MODULE_P33, 5};
IfxPort_Pin IfxPort_P33_6 = {&MODULE_P33, 6};
IfxPort_Pin IfxPort_P33_7 = {&MODULE_P33, 7};
IfxPort_Pin IfxPort_P33_8 = {&MODULE_P33, 8};
IfxPort_Pin IfxPort_P33_9 = {&MODULE_P33, 9};
IfxPort_Pin IfxPort_P40_4 = {&MODULE_P40, 4};
IfxPort_Pin IfxPort_P40_5 = {&MODULE_P40, 5};
IfxPort_Pin IfxPort_P40_6 = {&MODULE_P40, 6};
IfxPort_Pin IfxPort_P40_7 = {&MODULE_P40, 7};
IfxPort_Pin IfxPort_P40_8 = {&MODULE_P40, 8};
IfxPort_Pin IfxPort_P40_9 = {&MODULE_P40, 9};


const IfxPort_Pin *IfxPort_Pin_pinTable[IFXPORT_PINMAP_NUM_MODULES][IFXPORT_PINMAP_PIN_NUM_ITEMS] = {
    {
        &IfxPort_P00_0,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        &IfxPort_P02_0,
        &IfxPort_P02_1,
        &IfxPort_P02_2,
        &IfxPort_P02_3,
        &IfxPort_P02_4,
        &IfxPort_P02_5,
        &IfxPort_P02_6,
        &IfxPort_P02_7,
        &IfxPort_P02_8,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        &IfxPort_P10_5,
        &IfxPort_P10_6,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        &IfxPort_P11_2,
        &IfxPort_P11_3,
        NULL_PTR,
        NULL_PTR,
        &IfxPort_P11_6,
        NULL_PTR,
        &IfxPort_P11_8,
        &IfxPort_P11_9,
        &IfxPort_P11_10,
        &IfxPort_P11_11,
        &IfxPort_P11_12,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        &IfxPort_P13_1,
        &IfxPort_P13_2,
        &IfxPort_P13_3,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        &IfxPort_P14_0,
        &IfxPort_P14_1,
        NULL_PTR,
        &IfxPort_P14_3,
        NULL_PTR,
        &IfxPort_P14_5,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        &IfxPort_P15_0,
        &IfxPort_P15_1,
        &IfxPort_P15_2,
        &IfxPort_P15_3,
        NULL_PTR,
        &IfxPort_P15_5,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        &IfxPort_P20_8,
        &IfxPort_P20_9,
        &IfxPort_P20_10,
        &IfxPort_P20_11,
        &IfxPort_P20_12,
        &IfxPort_P20_13,
        &IfxPort_P20_14
    },
    {
        NULL_PTR,
        NULL_PTR,
        &IfxPort_P21_2,
        &IfxPort_P21_3,
        &IfxPort_P21_4,
        NULL_PTR,
        &IfxPort_P21_6,
        &IfxPort_P21_7,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        &IfxPort_P23_1,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        &IfxPort_P33_5,
        &IfxPort_P33_6,
        &IfxPort_P33_7,
        &IfxPort_P33_8,
        &IfxPort_P33_9,
        &IfxPort_P33_10,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    },
    {
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        &IfxPort_P40_4,
        &IfxPort_P40_5,
        &IfxPort_P40_6,
        &IfxPort_P40_7,
        &IfxPort_P40_8,
        &IfxPort_P40_9,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR,
        NULL_PTR
    }
};
#endif
#if defined (_TASKING_) || defined (_ghs_)
#pragma restore
#endif
