
/*********************************************************************************************************************/
/*! \file Cpu0_Main.c
 *  \brief TLE5502 Magnetic Position Sensor - On-The-Go Calibration with Parallel ADC Conversions
 *  \details This application demonstrates synchronous 4-channel ADC sampling of TLE5502 sensor outputs
 *           using CCU60-triggered parallel conversions across VADC groups, with continuous dynamic
 *           calibration (on-the-go) and real-time calibrated angle calculation with integrated safety mechanisms.
 *
 *  \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/* ==================== Includes ==================== */
#include <adc_sync4_ccu.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxSrc.h"
#include "IfxCpu_Irq.h"
#include <ongocalib.h>
#include <stdio.h>

/* ==================== Hardware Pin Mapping ==================== */
/**
 * TLE5502 Sensor Signal Connections:
 *
 * AN3  (VADCG0.3) - SINP  (Sine Positive)
 * AN8  (VADCG1.0) - COSP  (Cosine Positive)
 * AN20 (VADCG2.4) - SINN  (Sine Negative)
 * AN24 (VADCG3.0) - COSN  (Cosine Negative)
 *
 * Each channel is connected to a separate VADC group for true parallel conversion.
 * CCU60 T12 timer generates SR3 trigger signal for synchronous sampling.
 */

/* ==================== Global Variables ==================== */
IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;     /**< CPU synchronization event */

static AdcSync4Ccu g_adc;                            /**< ADC synchronous readout handler */

volatile float angle_read = 0;                       /**< Calibrated angle output in degrees */

/* Raw ADC values (12-bit LSB) - for debug/monitoring */
uint16 an3;                                          /**< Raw SINP value */
uint16 an8;                                          /**< Raw COSP value */
uint16 an20;                                         /**< Raw SINN value */
uint16 an24;                                         /**< Raw COSN value */

/* ==================== Main Function ==================== */
/**
 * \brief Main application entry point for CPU0
 * \details Performs the following sequence:
 *          1. Initialize peripherals (VADC + CCU60)
 *          2. Continuously calibrate during rotation (on-the-go method)
 *          3. Calculate calibrated angle with safety checks
 *
 * \note ON-THE-GO CALIBRATION METHOD:
 *       - Requires continuous one-directional rotation
 *       - Automatically updates calibration parameters every 1-2 rotations
 *       - No manual CW/CCW rotation procedure needed
 *       - Suitable for motors, fans, pumps, and continuous rotation applications
 */
void core0_main(void)
{
    /* ==================== Watchdog Disable ==================== */
    /* IMPORTANT: Watchdogs are disabled for development/debugging.
     * In production, enable and service them periodically. */
    IfxCpu_enableInterrupts();
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* ==================== Peripheral Initialization ==================== */
    AdcSync4Ccu_init(&g_adc);       /* Initialize VADC groups and CCU60 timer */
    AdcSync4Ccu_start(&g_adc);      /* Start CCU60 timer triggering */

    /* ==================== Calibration Data Structure ==================== */
    ONGO_CALIB_DATA_t calibration_store_params;

    /* Sensor data variables (LSB values from 12-bit ADC) */
    uint32_t sinP_in_LSB = 0;
    uint32_t cosP_in_LSB = 0;
    uint32_t sinN_in_LSB = 0;
    uint32_t cosN_in_LSB = 0;

    /* ==================== Initial Sensor Readout ==================== */
    /* Perform initial reading to populate calibration data structure */
    if (AdcSync4Ccu_fetchNewSetFlag(&g_adc))
    {
        sinP_in_LSB = AdcSync4Ccu_getRawAN3(&g_adc);
        cosP_in_LSB = AdcSync4Ccu_getRawAN8(&g_adc);
        sinN_in_LSB = AdcSync4Ccu_getRawAN20(&g_adc);
        cosN_in_LSB = AdcSync4Ccu_getRawAN24(&g_adc);

        ONGO_InitCalibData3(&calibration_store_params);  /* Initialize with automatic defaults */
        ONGO_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);
    }

    /* Safety mechanism counters */
    int fails = 0;
    int passes = 0;

    /* ==================== Main Application Loop ==================== */
    /**
     * CONTINUOUS OPERATION MODE:
     *
     * The on-the-go calibration runs continuously during normal operation:
     * - Tracks min/max values for all 4 channels
     * - Detects angle checkpoints at 45�� and 135��
     * - Recalculates calibration parameters every 1-2 rotations
     * - Compensates for temperature drift and aging effects
     *
     * Calibration converges after first 1-2 rotations and maintains accuracy indefinitely.
     */
    while (1)
    {
        if (AdcSync4Ccu_fetchNewSetFlag(&g_adc))
        {
            /* Read all 4 channels synchronously */
            sinP_in_LSB = AdcSync4Ccu_getRawAN3(&g_adc);
            cosP_in_LSB = AdcSync4Ccu_getRawAN8(&g_adc);
            sinN_in_LSB = AdcSync4Ccu_getRawAN20(&g_adc);
            cosN_in_LSB = AdcSync4Ccu_getRawAN24(&g_adc);

            /* ==================== Continuous Calibration ==================== */
            /**
             * Calibration is performed continuously in every full rotation measurement
             * to achieve high angle accuracy. This method is suitable for one-way
             * rotation applications.
             */
            ONGO_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);
            ONGO_CalibrationFindParam(&calibration_store_params);

            /* ==================== Safety Mechanism Checks ==================== */

            /* SME1: Angle Comparison (��P vs ��N) */
            if (SME1_angleComparison_AutoCalibration(&calibration_store_params))
            {
                passes++;
            }
            else
            {
                fails++;  /* Potential sensor fault or magnetic field disturbance */
            }

            /* SME2_1: Vector Length Check (N channels) */
            if (SME2_1_vectorLength_AutoCalibration(&calibration_store_params))
            {
                passes++;
            }
            else
            {
                fails++;  /* Signal amplitude out of expected range */
            }

            /* SME2_2: Vector Length Check (P channels) */
            if (SME2_2_vectorLengthCheck_AutoCalibration(&calibration_store_params))
            {
                passes++;
            }
            else
            {
                fails++;  /* Positive channel signal integrity issue */
            }

            /* SME2_3: Vector Length Check (Differential) */
            if (SME2_3_vectorLengthCheck_AutoCalibration(&calibration_store_params))
            {
                passes++;
            }
            else
            {
                fails++;  /* Differential signal magnitude issue */
            }

            /* SME3: Common Mode Check (Vcm_sin and Vcm_cos) */
            if (SME3_commonModeCheck(&calibration_store_params))
            {
                passes++;
            }
            else
            {
                fails++;  /* Common mode voltage deviation detected */
            }

            /* ==================== Calculate Calibrated Angle ==================== */
            angle_read = ONGO_GetCalibAngle(&calibration_store_params);
            passes++;

            /*
             * APPLICATION NOTE:
             * Monitor the fails/passes ratio. A high failure rate indicates:
             * - Sensor connection issues
             * - Magnetic field interference
             * - Mechanical misalignment
             * - Weak magnet or large airgap
             *
             * Calibration accuracy improves after first 1-2 rotations and is
             * maintained continuously through automatic parameter updates.
             */
        }
    } /* End of main loop */
}
