/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \brief TLE5502 Magnetic Position Sensor - One-Time Calibration with Parallel ADC Conversions
 * \details This application demonstrates synchronous 4-channel ADC sampling of TLE5502 sensor outputs
 *          using CCU60-triggered parallel conversions across VADC groups, followed by one-time
 *          calibration (CW and CCW rotations) and real-time calibrated angle calculation with
 *          integrated safety mechanisms.
 *
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/* ==================== Includes ==================== */
#include <adc_sync4_ccu.h>
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxSrc.h"
#include "IfxCpu_Irq.h"
#include <onecalib.h>
#include <stdio.h>

/* ==================== Hardware Pin Mapping ==================== */
/**
 * TLE5502 Sensor Signal Connections:
 *
 * AN3  (VADCG0.3) - SINP  (Sine Positive)
 * AN8  (VADCG1.0) - COSP  (Cosine Positive)
 * AN20 (VADCG2.4) - SINN  (Sine Negative)
 * AN24 (VADCG3.0) - COSN  (Cosine Negative)
 *
 * Each channel is connected to a separate VADC group for true parallel conversion.
 * CCU60 T12 timer generates SR3 trigger signal for synchronous sampling.
 */

/* ==================== Global Variables ==================== */
IFX_ALIGN(4) IfxCpu_syncEvent cpuSyncEvent = 0;     /**< CPU synchronization event */

static AdcSync4Ccu g_adc;                            /**< ADC synchronous readout handler */

volatile float angle_read = 0;                       /**< Calibrated angle output in degrees */

/* Raw ADC values (12-bit LSB) - for debug/monitoring */
uint16 an3;                                          /**< Raw SINP value */
uint16 an8;                                          /**< Raw COSP value */
uint16 an20;                                         /**< Raw SINN value */
uint16 an24;                                         /**< Raw COSN value */

/* ==================== Main Function ==================== */
/**
 * \brief Main application entry point for CPU0
 * \details Performs the following sequence:
 *          1. Initialize peripherals (VADC + CCU60)
 *          2. Perform clockwise (CW) rotation calibration
 *          3. Perform counter-clockwise (CCW) rotation calibration
 *          4. Enter normal operation mode with safety checks
 */
void core0_main(void)
{
    /* ==================== Watchdog Disable ==================== */
    /* IMPORTANT: Watchdogs are disabled for development/debugging.
     * In production, enable and service them periodically. */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* ==================== Peripheral Initialization ==================== */
    AdcSync4Ccu_init(&g_adc);       /* Initialize VADC groups and CCU60 timer */
    AdcSync4Ccu_start(&g_adc);      /* Start CCU60 timer triggering */

    /* ==================== Calibration Data Structures ==================== */
    CALIB_DATA_t calibration_store_params;
    ONECALIB_InitCalibData(&calibration_store_params);

    /* Sensor data variables (LSB values from 12-bit ADC) */
    volatile uint32_t sinP_in_LSB = 0;
    volatile uint32_t cosP_in_LSB = 0;
    volatile uint32_t sinN_in_LSB = 0;
    volatile uint32_t cosN_in_LSB = 0;

    /* ==================== Initial Sensor Readout ==================== */
    /* Perform initial reading to populate calibration data structure */
    {
        sinP_in_LSB = AdcSync4Ccu_getRawAN3(&g_adc);
        cosP_in_LSB = AdcSync4Ccu_getRawAN8(&g_adc);
        sinN_in_LSB = AdcSync4Ccu_getRawAN20(&g_adc);
        cosN_in_LSB = AdcSync4Ccu_getRawAN24(&g_adc);

        ONECALIB_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);
    }

    /* Safety mechanism counters */
    int fails = 0;
    int passes = 0;

    /* ==================== Main Application Loop ==================== */
    while (1)
    {
        /* ==================== PHASE 1: Clockwise (CW) Calibration ==================== */
        /**
         * USER ACTION REQUIRED: Rotate the magnet/sensor ONE FULL CLOCKWISE ROTATION
         *
         * The algorithm collects min/max values and specific angle points (45°, 135°, etc.)
         * to calculate amplitude, offset, and orthogonality parameters.
         */
        while (!calibration_store_params.rotation_data_CW.calibration_done)
        {
            /* Force ISR to ensure fresh data is available */
            AdcSync4Ccu_forceIsr(&g_adc);

            /* Read all 4 channels synchronously */
            sinP_in_LSB = AdcSync4Ccu_getRawAN3(&g_adc);
            cosP_in_LSB = AdcSync4Ccu_getRawAN8(&g_adc);
            sinN_in_LSB = AdcSync4Ccu_getRawAN20(&g_adc);
            cosN_in_LSB = AdcSync4Ccu_getRawAN24(&g_adc);

            /* Feed data to calibration algorithm */
            ONECALIB_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);
            ONECALIB_CalibrationFindParam(&calibration_store_params, TRUE, FALSE);
        }

        /* ==================== PHASE 2: Counter-Clockwise (CCW) Calibration ==================== */
        /**
         * USER ACTION REQUIRED: Rotate the magnet/sensor ONE FULL COUNTER-CLOCKWISE ROTATION
         *
         * The CCW rotation compensates for mechanical asymmetries and hysteresis effects.
         * After both CW and CCW calibrations, mean values are calculated for optimal accuracy.
         */
        AdcSync4Ccu_stop(&g_adc);  /* Stop automatic triggering (optional) */

        while (!calibration_store_params.rotation_data_CCW.calibration_done)
        {
            /* Read sensor data (can use manual trigger or polled reading) */
            sinP_in_LSB = AdcSync4Ccu_getRawAN3(&g_adc);
            cosP_in_LSB = AdcSync4Ccu_getRawAN8(&g_adc);
            sinN_in_LSB = AdcSync4Ccu_getRawAN20(&g_adc);
            cosN_in_LSB = AdcSync4Ccu_getRawAN24(&g_adc);

            ONECALIB_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);
            ONECALIB_CalibrationFindParam(&calibration_store_params, FALSE, TRUE);
        }

        /* ==================== PHASE 3: Normal Operation with Safety Checks ==================== */
        /**
         * Calibration complete! Now entering continuous angle measurement mode.
         * Safety mechanisms continuously monitor signal integrity.
         */
        if (AdcSync4Ccu_fetchNewSetFlag(&g_adc))
        {
            /* Read latest synchronized ADC values */
            sinP_in_LSB = AdcSync4Ccu_getRawAN3(&g_adc);
            cosP_in_LSB = AdcSync4Ccu_getRawAN8(&g_adc);
            sinN_in_LSB = AdcSync4Ccu_getRawAN20(&g_adc);
            cosN_in_LSB = AdcSync4Ccu_getRawAN24(&g_adc);

            /* Calculate calibrated angle if calibration is complete */
            if (calibration_store_params.full_calibration_performed)
            {
                ONECALIB_InitSensorData(sinP_in_LSB, cosP_in_LSB, sinN_in_LSB, cosN_in_LSB);
                angle_read = ONECALIB_GetCalibAngle(&calibration_store_params);

                /* ==================== Safety Mechanism Checks ==================== */

                /* SME1: Angle Comparison (αP vs αN) */
                if (SME1_angleComparison_OneTimeCompensation(&calibration_store_params))
                {
                    passes++;
                }
                else
                {
                    fails++;  /* Potential sensor fault or magnetic field disturbance */
                }

                /* SME2_1: Vector Length Check (VP and VN) */
                if (SME2_1_vectorLengthCheck_OneTimeCompensation(&calibration_store_params))
                {
                    passes++;
                }
                else
                {
                    fails++;  /* Signal amplitude out of expected range */
                }

                /* SME2_2: Vector Length Check (VP only) */
                if (SME2_2_vectorLengthCheck_OneTimeCompensation(&calibration_store_params))
                {
                    passes++;
                }
                else
                {
                    fails++;  /* Positive channel signal integrity issue */
                }

                /* SME2_3: Vector Length Check (Differential) */
                if (SME2_3_vectorLengthCheck_OneTimeCompensation(&calibration_store_params))
                {
                    passes++;
                }
                else
                {
                    fails++;  /* Differential signal magnitude issue */
                }

                /* SME3: Common Mode Check (Vcm_sin and Vcm_cos) */
                if (SME3_commonModeCheck_OneTimeCompensation(&calibration_store_params))
                {
                    passes++;
                }
                else
                {
                    fails++;  /* Common mode voltage deviation detected */
                }

                /*
                 * APPLICATION NOTE:
                 * Monitor the fails/passes ratio. A high failure rate indicates:
                 * - Sensor connection issues
                 * - Magnetic field interference
                 * - Mechanical misalignment
                 * - Temperature drift (consider dynamic calibration)
                 */
            }
        }
    } /* End of main loop */
}
