/**********************************************************************************************************************
 * \file TLx49012.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef SRC_TLX49012_TLX49012_TLX49012_H_
#define SRC_TLX49012_TLX49012_TLX49012_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "time.h"
#include "SPI_Frontend.h"
#include "CRC8_SAE_J1850.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
// UNLOCK
#define UNLOCK_REG_ADDR             0x78
#define USR_PASS_DATA               0x4711

// CRC BITMAP DISABLE
#define STAT_EN_1_REG_ADDR          0x04
#define CRC_BM_DIS_DATA             0x7F18

// USER CONFIG 1 - holds sync pulse configuration
#define USR_CONFIG_1_ADDR           0x3F
// SPI + SYNC ON IFE + FALLING EDGE SYNC (SPI CONFIG VALID ONLY FOR S0001 & E0001) - CHECK VARIANT
#define USR_CONFIG_1_DATA           0x400

// PREDICTED ANGLE REGISTER
#define ANGLE_PRED_ADDR             0x0C

// ANGLE REGISTER
#define ANGLE_ADDR                  0x0F

// ANGLE SYNC REGISTER
#define ANGLE_SYNC_ADDR             0x0A
#define SYNC_READ_STATUS_MASK       0x1
#define SYNC_TRIG_STATUS_MASK       0x2
#define SYNC_ANGLE_MASK             0xFFFC

// STATUS / RESET REGISTER
#define STAT_EN_REG_ADDR            0x02
#define VAL_SOFT_RESET_VM_DATA      0x8E82
#define VAL_SOFT_RESET_NVM_DATA     0x8E81



/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
 static uint16 g_CRC_raw = 0;
 static uint16 g_angle_raw = 0;
 static uint16 g_status_raw = 0;

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
/*******************************************************************************
 * Function Name: TLx49012_Init
 ***************************************************************************//**
 * \brief   Initializes the sensor through a series of SPI commands.
            Soft-resets the sensor.
            Disables self-calibration.
 ******************************************************************************/
void TLx49012_Init(void);


/*******************************************************************************
 * Function Name: TLx49012_GetAngleLSB
 ***************************************************************************//**
 * \brief   Reads the internal register at address 15 via SPI.
 * \return  Angle value in LSB, 16-bit.
 ******************************************************************************/
uint16 TLx49012_GetAngleLSB(void);


/*******************************************************************************
 * Function Name: TLx49012_GetAngleDegrees
 ***************************************************************************//**
 * \brief   Reads the internal register at address 12 via SPI.
 * \return  Angle value in degrees, double precision.
 ******************************************************************************/
double TLx49012_GetAngleDegrees(void);


/*******************************************************************************
 * Function Name: TLx49012_PrintSerialData
 ***************************************************************************//**
 * \brief   Pushes through UART the values stored in the global variables
 *        of Device Status, Raw Angle, CRC, Angle [degrees]
 ******************************************************************************/
void TLx49012_PrintSerialData(void);


#endif /* SRC_TLX49012_TLX49012_TLX49012_H_ */
