/**********************************************************************************************************************
 * \file TLx49012.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "TLx49012.h"
#include "uart.h"
#include "time.h"
#include "SPI_Frontend.h"
#include "CRC8_SAE_J1850.h"

#include <stdint.h>
#include <stdio.h>


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
double angle = 0;

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void TLx49012_Init(void)
{
    char buf[200];
    int len = 0;

    //Print data based on operating mode and setting
    len = sprintf(buf, "\n\n\n\nSensor initialization in progress...\r\n" );
    UART_send_buf(buf, (uint16)len);

    // Populate CRC LUT
    CRCInit();

    // Wait for SPI to become active - ASSUME JUST POWERED ON
    TIME_wait_us(550);

    //Print data based on operating mode and setting
    len = sprintf(buf, "Unlocking sensor...\r\n" );
    UART_send_buf(buf, (uint16)len);
    SpiWriteInFrame(UNLOCK_REG_ADDR, USR_PASS_DATA);

    // Disable Bitmap CRC checks
    len = sprintf(buf, "Disabling CRC checks for bitmaps...\r\n" );
    UART_send_buf(buf, (uint16)len);
    SpiWriteInFrame(STAT_EN_1_REG_ADDR, CRC_BM_DIS_DATA);

    // Test sensor responses
    uint32_t dataTest;
    dataTest = SpiReadInFrame(STAT_EN_1_REG_ADDR, true);
    if(((dataTest & 0x00FFFF00) >> 8) != CRC_BM_DIS_DATA)
    {
        while(1)
        {
            len = sprintf(buf, "ERROR: Sensor not responding or locked\r\n" );
            UART_send_buf(buf, (uint16)len);

            TIME_wait_ms(5000);
        }
    }

    // Soft configure sensor
    len = sprintf(buf, "Configuring sensor...\r\n" );
    UART_send_buf(buf, (uint16)len);
    SpiWriteInFrame(USR_CONFIG_1_ADDR, USR_CONFIG_1_DATA);

    // Reset sensor from VM memory - keep and apply configuration
    len = sprintf(buf, "Resetting sensor...\r\n");
    UART_send_buf(buf, (uint16)len);
    SpiWriteInFrame(STAT_EN_REG_ADDR, VAL_SOFT_RESET_VM_DATA);

    // Wait for SPI to become active
    TIME_wait_us(900);

    // Configuration check after reset
    dataTest = SpiReadInFrame(USR_CONFIG_1_ADDR, true);
    if(((dataTest & 0x00FFFF00) >> 8) != USR_CONFIG_1_DATA)
    {
        while(1)
        {
            len = sprintf(buf, "ERROR: Sensor not configured correctly\r\n" );
            UART_send_buf(buf, (uint16)len);

            TIME_wait_ms(5000);
        }
    }


    len = sprintf(buf, "Sensor initializations DONE!\r\n" );
    UART_send_buf(buf, (uint16)len);
}

uint16 TLx49012_GetAngleLSB( void )
{
    uint32 sensor_response;

    /* Read out the ANGLE_PRED_ADDR register */
    sensor_response = SpiReadInFrame(ANGLE_PRED_ADDR, true);

    /* Return the sensor response truncated to only the data bits */
    return (uint16)((sensor_response & 0x00FFFF00) >> 8);
}


double TLx49012_GetAngleDegrees( void )
{
   /* Read the ANGLE_PRED_REG which is at address 12 (0x0C) */
   uint32 data_Rx = SpiReadInFrame(ANGLE_PRED_ADDR, true);

   /* Split the Received data */
   g_CRC_raw = data_Rx & 0xFF;
   g_angle_raw = (data_Rx >> 8) & 0xFFFF;
   g_status_raw = (data_Rx >> 24) & 0xFF;

   /* Compute angle */
   angle = (g_angle_raw * 360.0f) / 65536;

   /* Return result */
   return angle;
}

void TLx49012_PrintSerialData(void)
{
    /* UART variables */
    char buf[200];
    int len = 0;

    /*Print global available data */
    len = sprintf(buf, "\nNEW FRAME\n"
                           "Device Status: 0x%02X\n"
                           "Angle [LSB16]: 0x%04X\n"
                           "CRC:           0x%02X\n"
                           "Angle [deg]:   %.2f\n\n",
                           g_status_raw,
                           g_angle_raw,
                           g_CRC_raw,
                           angle
                );


    /* Send data via UART */
    UART_send_buf(buf, (uint16)len);

}

