/*
 * UVISION generated file: DO NOT EDIT!
 * Generated by: uVision version 5.43.1.0
 *
 * Project: 'TLE5502_TLE987x_Integration_Example' 
 * Target:  'src' 
 */

#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H


/*
 * Define the Device Header File: 
 */
#define CMSIS_device_header "tle987x.h"

/* Infineon::Device:ConfigWizard_v2@2.1.12 */
#define CONFIGWIZARD 2
/* Infineon::Device:SDK:ADC1@0.3.1 */
#define RTE_DEVICE_SDK_ADC1
/* Infineon::Device:SDK:ADC2@0.2.7 */
#define RTE_DEVICE_SDK_ADC2
/* Infineon::Device:SDK:BOOTROM@0.3.4 */
#define RTE_DEVICE_SDK_BROM
/* Infineon::Device:SDK:DMA@0.2.7 */
#define RTE_DEVICE_SDK_DMA
/* Infineon::Device:SDK:INT@0.2.4 */
#define RTE_DEVICE_SDK_INT
/* Infineon::Device:SDK:ISR@0.3.0 */
#define RTE_DEVICE_SDK_ISR
/* Infineon::Device:SDK:LIN@0.2.1 */
#define RTE_DEVICE_SDK_LIN
/* Infineon::Device:SDK:PMU@0.2.3 */
#define RTE_DEVICE_SDK_PMU
/* Infineon::Device:SDK:PORT@0.6.1 */
#define RTE_DEVICE_SDK_PORT
/* Infineon::Device:SDK:SCU@0.5.9 */
#define RTE_DEVICE_SDK_SCU
/* Infineon::Device:SDK:UART@0.2.5 */
#define RTE_DEVICE_SDK_UART
/* Infineon::Device:SDK:WDT1@0.3.4 */
#define RTE_DEVICE_SDK_WDT1
/* Keil::Compiler&ARM Compiler:I/O:STDIN&User@1.2.0 */
#define RTE_Compiler_IO_STDIN           /* Compiler I/O: STDIN */
#define RTE_Compiler_IO_STDIN_User      /* Compiler I/O: STDIN User */
/* Keil::Compiler&ARM Compiler:I/O:STDOUT&User@1.2.0 */
#define RTE_Compiler_IO_STDOUT          /* Compiler I/O: STDOUT */
#define RTE_Compiler_IO_STDOUT_User     /* Compiler I/O: STDOUT User */
/* Keil::Compiler&ARM Compiler:I/O:TTY&User@1.2.0 */
#define RTE_Compiler_IO_TTY             /* Compiler I/O: TTY */
#define RTE_Compiler_IO_TTY_User        /* Compiler I/O: TTY User */


#endif /* RTE_COMPONENTS_H */
