/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 /*\title TLx49012 TC375 LK SPI Angle Decoding and Processing
 * \abstract Example code for TLx49012 magnetic angle sensor integration with TC375 Aurix MCU with SPI communication
 * \description Exemplifies:
 *              1.	SPI communication with the TLx49012 magnetic angle sensor.
 *              2.	CRC calculations
 *              3.	OneEye UI
 *
 * \name TLx49012 TC375 LK SPI Integration Example
 * \version V1.0.0
 * \board AURIX TC375 lite Kit, KIT_A2G_TC375_LITE, TC37xTP_A-Step
 * \keywords AURIX, Communication, Master, TC375 LK, SPI, SPI_CPU_1, Magnetic, Sensor, TLx49012, Example Code, Integration
 * \documents README.MD
 * \documents https://www.infineon.com/aurix-expert-training/TC37A_iLLD_UM_1_0_1_17_0.chm
 * \lastUpdated 2024-04-18
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "uart.h"
#include "time.h"
#include "SPI_Frontend.h"
#include "CRC8_SAE_J1850.h"

#include <stdint.h>
#include <stdio.h>

#include "TLx49012.h"

static float g_angle = 0;

IFX_ALIGN(4) IfxCpu_syncEvent g_cpuSyncEvent = 0;

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watch dogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    /* Initialise the SPI */
    InitSPI();

    /* Initialise the UART channel */
    UART_init();

    /* Initialise the Sensor */
    TLx49012_Init();


    while(1)
    {
        /* Get Angle */
        double Angle = TLx49012_GetAngleDegrees();

        /* Rounding for OneEye UI display */
        g_angle = (int)(Angle * 100) / 100.0f;

        /* Print out the global variables through the UART channel */
        TLx49012_PrintSerialData();

        /* Delay for sample rate control */
        TIME_wait_us(500);                          // Wait x
    }
}





